version: 2.1

commands:
  dreamai-with-missforest:
    parameters:
      useMissForest:
        type: string
        default: 'true'
    steps:
      - checkout
      - run:
          name: Install dependencies to VM
          command: pip3 install cwltool
      - run:
          name: Test dreamAI
          command: cwltool imputation-tool.cwl --input_f=TOY_log2ratio_protein_abundance_withNA.tsv --use_missForest=<<parameters.useMissForest>>
          no_output_timeout: 5h
      - run:
          name: move artifacts to tmp
          command: mkdir /tmp && mv ~/project/imputed_file.tsv /tmp
      - store_artifacts:
          path: /tmp

executors:
  ubuntu-large:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
  ubuntu-medium:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium

workflows:
  test-timings:
    jobs:
#      - dreamAI-large
#      - dreamAI-medium
#      - dreamAI-large-no-missforest
      - dreamAI-medium-no-missforest

jobs:
  dreamAI-large:
    executor: ubuntu-large
    steps:
      - dreamai-with-missforest
  dreamAI-medium:
    executor: ubuntu-medium
    steps:
      - dreamai-with-missforest
  dreamAI-large-no-missforest:
    executor: ubuntu-large
    steps:
      - dreamai-with-missforest:
          useMissForest: 'false'
  dreamAI-medium-no-missforest:
    executor: ubuntu-medium
    steps:
      - dreamai-with-missforest:
          useMissForest: 'false'