version: 2.1

commands:
  dreamai-with-missforest:
    steps:
      - checkout
      - run:
          name: Install dependencies to VM
          command: pip3 install cwltool
      - run:
          name: Test dreamAI
          command: cwltool imputation-tool.cwl --input_f=TOY_log2ratio_protein_abundance_withNA.tsv --use_missForest=false

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large

workflows:
  test-timings:
    jobs:
      - dreamAI

jobs:
  dreamAI:
    executor: ubuntu
    steps:
      - dreamai-with-missforest
