version: 2.1

commands:
  dreamai-with-missforest:
    parameters:
      useMissForest:
        type: string
        default: 'true'
    steps:
      - checkout
      - run:
          name: Install dependencies to VM
          command: pip3 install cwltool
      - run:
          name: Test dreamAI
          command: cwltool imputation-tool.cwl --input_f=TEST_50pfilter_6_CPTAC3_CCRCC_Whole_abundance_gene_protNorm_2_CB_clean_1105.tsv --use_missForest=<<parameters.useMissForest>>
          no_output_timeout: 5h
      - run:
          name: mv and save artifacts
          command: mkdir artifacts && mv imputed_file.tsv artifacts/imputed_file.tsv
      - store_artifacts:
          path: artifacts

executors:
  ubuntu-large:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
  ubuntu-medium:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium

workflows:
  test-timings:
    jobs:
      - dreamAI-large
      - dreamAI-medium
      - dreamAI-large-no-missforest
      - dreamAI-medium-no-missforest

jobs:
  dreamAI-large:
    executor: ubuntu-large
    steps:
      - dreamai-with-missforest
  dreamAI-medium:
    executor: ubuntu-medium
    steps:
      - dreamai-with-missforest
  dreamAI-large-no-missforest:
    executor: ubuntu-large
    steps:
      - dreamai-with-missforest:
          useMissForest: 'false'
  dreamAI-medium-no-missforest:
    executor: ubuntu-medium
    steps:
      - dreamai-with-missforest:
          useMissForest: 'false'